spring:
  config:
    activate:
      on-profile: docker

  r2dbc:
    url: r2dbc:h2:file:///./data/scoreassistant;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE

logging:
  structured:
    format:
      console: logstash
    json:
      rename:
        level: severity
        "[@timestamp]": timestamp
      add:
        version: ${APP_VERSION:unknown}
