spring:
  application:
    name: vocabest-core
  r2dbc:
    url: r2dbc:h2:mem:///vocabest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 

  datasource:
    url: jdbc:h2:mem:vocabest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
vocabest:
  admin:
    whitelist: linus.chien@gmail.com
  security:
    mock-user-email: "dev@vocabest.engineer"
