// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import React from 'react';
import { shadcnComponents } from '@json-render/shadcn';
import { useStateStore } from '@json-render/react';
import type { ComponentType } from 'react';

// Import custom components from the components directory (one component per file)
import DataTable from './components/DataTable';
import Breadcrumb from './components/Breadcrumb';
import AlertDialog from './components/AlertDialog';
import MetricCard from './components/MetricCard';
import UserMenuDropdown from './components/UserMenuDropdown';
import ErrorReviewButton from './components/ErrorReviewButton';
import ProgressTimeControls from './components/ProgressTimeControls';
import ProgressChart from './components/ProgressChart';
import WordleGame from './components/WordleGame';
import CrosswordGame from './components/CrosswordGame';
import MemoryGame from './components/MemoryGame';
import CriticalMissionLogViewer from './components/CriticalMissionLogViewer';

// ── Adapter: ComponentRenderProps → BaseComponentProps ──────────────────────
function adapt(Comp: ComponentType<any>): ComponentType<any> {
  const Adapted: ComponentType<any> = ({ element, children, emit, on, bindings, loading }: any) => {
    let store: any;
    try { store = useStateStore(); } catch { store = null; }

    // Intercept button press to auto-close modals and trigger toasts
    const customEmit = (eventName: string, ...args: any[]) => {
      if (eventName === 'press' && store) {
        const id = element?.props?.id ?? '';
        const label = element?.props?.label ?? '';
        const isClosingAction =
          label === '取消' || label === '儲存' || label === '確認刪除' || label === 'Save' || label === 'Confirm' || label === 'Confirm Deletion' ||
          id.includes('cancel') || id.includes('submit') || id.includes('confirm');
        if (isClosingAction) {
          const modals = store.get('/modals') || {};
          store.set('/modals', Object.fromEntries(Object.keys(modals).map(k => [k, false])));
        }
      }
      if (emit) emit(eventName, ...args);
    };

    // Admin-only visibility filtering
    if (element?.props?.adminOnly) {
      if (!store || store.get('/data/user/role') !== 'ADMIN') {
        return null;
      }
    }

    return React.createElement(Comp, {
      props: element?.props ?? {},
      children,
      emit: customEmit,
      on,
      bindings,
      loading,
    });
  };
  Adapted.displayName = `Adapted(${(Comp as any).displayName || Comp.name || 'Component'})`;
  return Adapted;
}

// ── Component Registry ──────────────────────────────────────────────────────
export const componentRegistry: Record<string, ComponentType<any>> = {
  // ── 1. All @json-render/shadcn presets, adapted ─────────────────────────
  ...Object.fromEntries(
    Object.entries(shadcnComponents).map(([key, Comp]) => [key, adapt(Comp as ComponentType<any>)])
  ),

  // ── 2. Custom layout shell ───────────────────────────────────────────────
  'Container:page': ({ children }) => (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">{children}</div>
  ),

  // Quiz-specific layout containers
  'Container:quiz-page': ({ children }) => (
    <div className="flex items-start justify-center min-h-[calc(100vh-80px)] px-4 py-10">{children}</div>
  ),
  'Container:quiz-card': ({ children }) => (
    <div className="w-full max-w-2xl bg-card border border-border rounded-2xl shadow-lg p-8 flex flex-col gap-8">{children}</div>
  ),
  'Container:quiz-header': ({ children }) => (
    <div className="flex items-center justify-between border-b border-border pb-4">{children}</div>
  ),
  'Container:question-block': ({ children }) => (
    <div className="flex flex-col gap-4 bg-muted/40 rounded-xl p-6">{children}</div>
  ),
  'Container:options-grid': ({ children }) => (
    <div className="grid grid-cols-2 gap-3">{children}</div>
  ),

  // Dictionary header: scroll icon + level title
  'Container:dict-header': ({ children }) => (
    <div className="flex items-center gap-3 pb-2 border-b border-border">{children}</div>
  ),

  // ── 3. Custom composites (imported from src/json-render/components/) ─────
  'DataTable':   DataTable,    // columns/data/row-actions
  'Breadcrumb':  Breadcrumb,   // <nav><ol> wrapper
  'AlertDialog': AlertDialog,  // confirm dialog overlay
  'MetricCard':  MetricCard,   // KPI metric card
  'UserMenuDropdown': adapt(UserMenuDropdown),
  'ErrorReviewButton': ErrorReviewButton, // 弱點特訓入口按鈕（含 badge）
  'ProgressTimeControls': adapt(ProgressTimeControls),
  'ProgressChart': adapt(ProgressChart),
  'WordleGame': adapt(WordleGame),
  'CrosswordGame': adapt(CrosswordGame),
  'MemoryGame': adapt(MemoryGame),
  'CriticalMissionLogViewer': adapt(CriticalMissionLogViewer),

  // ── 5. Native HTML passthrough ───────────────────────────────────────────
  'div': ({ element, children }: any) => (
    <div className={element?.props?.className} id={element?.props?.id}>{children}</div>
  ),
  'span': ({ element, children }: any) => (
    <span className={element?.props?.className} id={element?.props?.id}>{children}</span>
  ),
  'button': ({ element, children, emit }: any) => (
    <button 
      className={element?.props?.className} 
      id={element?.props?.id}
      disabled={!!element?.props?.disabled}
      onClick={() => emit && emit('press')}
    >
      {element?.props?.label || children}
    </button>
  ),
  'Text': ({ element, children }: any) => {
    const text = element?.props?.text;
    const resolvedText = typeof text === 'object' && text.$state ? undefined : text; // json-render handles $state binding to props natively if we use the right key
    // Actually, json-render automatically resolves $state inside element.props.
    return <span className={element?.props?.className} id={element?.props?.id}>{element?.props?.text || children}</span>;
  },
};
