@startuml sys-vocabest-core-api-midnight-reset-of-daily-progress

!pragma layout smetana
skinparam defaultFontName Inter

participant "DomainLogic" as Domain
participant "DailyProgressRepositoryAdapter" as SecondaryAdapter <<Secondary>>

note over Domain: Triggered upon Learner Login\nEvaluates if progress is from previous day

Domain -> SecondaryAdapter : findById(id: UUID)
activate SecondaryAdapter
SecondaryAdapter --> Domain : Optional<DailyProgress>
deactivate SecondaryAdapter

opt is new day
    Domain -> SecondaryAdapter : save(entity: DailyProgress)
    activate SecondaryAdapter
    SecondaryAdapter --> Domain : DailyProgress
    deactivate SecondaryAdapter
end

@enduml
