@startuml sys-vocabest-core-api-midnight-reset-of-daily-progress

!pragma layout smetana
skinparam defaultFontName Inter

participant "InternalScheduler" as Scheduler
participant "DailyProgressRepositoryAdapter" as SecondaryAdapter <<Secondary>>

Scheduler -> SecondaryAdapter : save(entity: DailyProgress)
activate SecondaryAdapter
SecondaryAdapter --> Scheduler : DailyProgress
deactivate SecondaryAdapter

@enduml
