@startuml user-vocabest-core-api-fetching-contextual-cloze-questions

!pragma layout smetana
skinparam defaultFontName Inter

actor Learner

box "vocabest-core-api"
  participant "UserRestControllerAdapter" as PrimaryAdapter <<Primary>>
  participant "UserQueryServiceAdapter" as DomainService <<Service>>
  participant "UserRepositoryAdapter" as SecondaryAdapter <<Secondary>>
end box

Learner -> PrimaryAdapter : getNextQuestion(userId: UUID)
activate PrimaryAdapter

PrimaryAdapter -> DomainService : getNextQuestion(userId)
activate DomainService

DomainService -> SecondaryAdapter : findById(id: UUID)
activate SecondaryAdapter
SecondaryAdapter --> DomainService : Optional<User>
deactivate SecondaryAdapter

DomainService --> PrimaryAdapter : QuizQuestionResponse
deactivate DomainService

PrimaryAdapter --> Learner : ResponseEntity<QuizQuestionResponse> (200 OK)
deactivate PrimaryAdapter

@enduml
