// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';

export interface WordBankResponse {
  id: string;
  word: string;
  partsOfSpeech?: string;
  chineseTranslation?: string;
  targetLevel: string;
}

export const memoryGameTargetKeys = {
  all: ['memoryGameTargets'] as const,
  byUser: (userId: string, count: number) => ['memoryGameTargets', userId, count] as const,
};

export function useGetMemoryGameTargets(userId?: string, count: number = 8) {
  return useQuery({
    queryKey: userId ? memoryGameTargetKeys.byUser(userId, count) : memoryGameTargetKeys.all,
    queryFn: async () => {
      if (!userId) throw new Error('User ID is required');
      const response = await fetch(`/api/v1/users/${userId}:memoryGameTargets?count=${count}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!response.ok) {
        throw new Error('Failed to fetch memory game targets');
      }
      return response.json() as Promise<WordBankResponse[]>;
    },
    enabled: !!userId && count > 0,
    refetchOnWindowFocus: false, // Prevent words from changing mid-game
    refetchOnMount: false,
    staleTime: Infinity,
  });
}
