// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export const getDailyProgressByIdKeys = {
  all: ['getDailyProgressById'] as const,
};

export function useGetDailyProgressById(params?: any) {
  return useQuery({
    queryKey: getDailyProgressByIdKeys.all,
    queryFn: () => api.get<any>('/users/' + params?.userId + '/daily-progresses/' + params?.id),
  });
}
