// AUTO-GENERATED by Frontend Engineer workflow
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export function useOnboardUser() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (payload: any) => api.post<void>('/onboardUser', payload),
    onSuccess: () => {
      queryClient.invalidateQueries();
    },
  });
}
