// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface ResponseType {
  [key: string]: unknown;
}

const QUERY = gql`
  query listWordBanks($filter: WordBankFilterInput) {
    listWordBanks(filter: $filter) {
      content {
        id
        word
        chineseTranslation
        targetLevel
        difficultyLevel
        partsOfSpeech
        examFrequency
      }
      totalElements
    }
  }
`;

export const listWordBanksKeys = {
  all: ['listWordBanks'] as const,
  filtered: (filter: any) => ['listWordBanks', filter] as const,
};

export function useListWordBanks(filter?: any) {
  return useQuery({
    queryKey: filter ? listWordBanksKeys.filtered(filter) : listWordBanksKeys.all,
    queryFn: () => request<{ listWordBanks: { content: ResponseType[], totalElements: number } }>(GRAPHQL_ENDPOINT, QUERY, filter ? { filter } : {}).then(data => data.listWordBanks),
  });
}
