// AUTO-GENERATED by Frontend Engineer workflow
import { useMutation } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export function useSubmitAnswer() {
  return useMutation({
    mutationFn: (payload: any) => api.post<void>('/users/' + payload?.userId + ':submitAnswer', payload),
    // Do NOT invalidateQueries here — the quiz page controls when to load the next question
    // (only after the user reads the explanation and clicks 下一題)
  });
}
