// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface WordBank {
  id: string;
  word: string;
  partsOfSpeech?: string;
  chineseTranslation?: string;
}

export interface QuizQuestion {
  id: string;
  wordBankId: string;
  contextualCloze: string;
  chineseTranslation?: string;
  correctAnswer: string;
  distractor1: string;
  distractor2?: string;
  distractor3?: string;
  explanationRootAffix?: string;
  explanationMnemonic?: string;
  wordBank: WordBank;
}

export interface ErrorEvent {
  id: string;
  userId: string;
  quizQuestionId: string;
  timestamp: string;
  selectedDistractor: string;
  quizQuestion: QuizQuestion;
}

export interface ErrorEventFilterInput {
  userId?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  size?: number;
}

const QUERY = gql`
  query listErrorEvents($filter: ErrorEventFilterInput) {
    listErrorEvents(filter: $filter) {
      content {
        id
        userId
        quizQuestionId
        timestamp
        selectedDistractor
        quizQuestion {
          id
          wordBankId
          contextualCloze
          chineseTranslation
          correctAnswer
          distractor1
          distractor2
          distractor3
          explanationRootAffix
          explanationMnemonic
          wordBank {
            id
            word
            partsOfSpeech
            chineseTranslation
          }
        }
      }
      totalElements
    }
  }
`;

export const listErrorEventsKeys = {
  all: ['listErrorEvents'] as const,
  filtered: (filter: ErrorEventFilterInput) => ['listErrorEvents', filter] as const,
};

export function useListErrorEvents(filter: ErrorEventFilterInput, enabled: boolean = true) {
  return useQuery({
    queryKey: listErrorEventsKeys.filtered(filter),
    queryFn: () => request<{ listErrorEvents: { content: ErrorEvent[], totalElements: number } }>(
      GRAPHQL_ENDPOINT, 
      QUERY, 
      { filter }
    ).then(data => data.listErrorEvents),
    enabled: !!filter.userId && enabled,
  });
}
