// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export const getNextQuestionKeys = {
  all: ['getNextQuestion'] as const,
};

export function useGetNextQuestion(params?: any) {
  return useQuery({
    queryKey: getNextQuestionKeys.all,
    queryFn: () => api.get<any>('/getNextQuestion', { params }),
  });
}
