// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface ErrorReviewCountResponse {
  count: number;
}

export const errorReviewCountKeys = {
  all: (userId: string) => ['errorReviewCount', userId] as const,
};

export function useGetErrorReviewCount(params?: { userId: string }) {
  return useQuery({
    queryKey: params ? errorReviewCountKeys.all(params.userId) : ['errorReviewCount'],
    queryFn: () => api.get<ErrorReviewCountResponse>('/users/' + params!.userId + ':errorReviewCount'),
    enabled: !!params?.userId,
    refetchOnWindowFocus: true,
  });
}
