// AUTO-GENERATED by Frontend Engineer workflow
import { useMutation } from '@tanstack/react-query';

export interface WordleValidationRequest {
  guess: string;
}

export interface WordleValidationResponse {
  valid: boolean;
}

export function useValidateWordleGuess() {
  return useMutation({
    mutationFn: async ({ userId, guess }: { userId: string; guess: string }) => {
      const response = await fetch(`/api/v1/users/${userId}:validateWordleGuess`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ guess }),
      });
      if (!response.ok) {
        throw new Error('Failed to validate wordle guess');
      }
      return response.json() as Promise<WordleValidationResponse>;
    },
  });
}
