// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface ResponseType {
  [key: string]: unknown;
}

const QUERY = gql`
  query listUsers($filter: UserFilterInput) {
    listUsers(filter: $filter) {
      id
      email
      role
      targetLevel
      learningStreak
      maxLearningStreak
      maxDailyQuestions
      dailyTargetQuestions
      stats {
        totalQuestionsAnswered
        totalCorrectAnswers
        overallAccuracy
      }
    }
  }
`;

export const listUsersKeys = {
  all: ['listUsers'] as const,
  filtered: (filter: any) => ['listUsers', filter] as const,
};

export function useListUsers(filter?: any) {
  return useQuery({
    queryKey: filter ? listUsersKeys.filtered(filter) : listUsersKeys.all,
    queryFn: () => request<{ listUsers: ResponseType[] }>(GRAPHQL_ENDPOINT, QUERY, filter ? { filter } : {}).then(data => data.listUsers),
  });
}
