// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export const getNextQuestionKeys = {
  all: (userId: string) => ['getNextQuestion', userId] as const,
};

export function useGetNextQuestion(params?: { userId: string }) {
  return useQuery({
    queryKey: params ? getNextQuestionKeys.all(params.userId) : ['getNextQuestion'],
    queryFn: () => api.post<any>('/users/' + params!.userId + ':nextQuestion'),
    enabled: !!params?.userId,
    // Do NOT auto-refetch; we manually refetch after each answer
    refetchOnWindowFocus: false,
    staleTime: Infinity,
  });
}
