// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export const getNextErrorQuestionKeys = {
  all: (userId: string) => ['getNextErrorQuestion', userId] as const,
};

export function useGetNextErrorQuestion(params?: { userId: string }) {
  return useQuery({
    queryKey: params ? getNextErrorQuestionKeys.all(params.userId) : ['getNextErrorQuestion'],
    queryFn: () => api.post<any>('/users/' + params!.userId + ':nextErrorQuestion'),
    enabled: !!params?.userId,
    refetchOnWindowFocus: false,
    gcTime: 0,
  });
}
