// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';

export interface WordBankResponse {
  id: string;
  word: string;
  partsOfSpeech?: string;
  chineseTranslation?: string;
  targetLevel: string;
}

export const crosswordTargetKeys = {
  all: ['crosswordTargets'] as const,
  byUser: (userId: string) => ['crosswordTargets', userId] as const,
};

export function useGetCrosswordTargets(userId?: string) {
  return useQuery({
    queryKey: userId ? crosswordTargetKeys.byUser(userId) : crosswordTargetKeys.all,
    queryFn: async () => {
      if (!userId) throw new Error('User ID is required');
      const response = await fetch(`/api/v1/users/${userId}:crosswordTargets`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!response.ok) {
        throw new Error('Failed to fetch crossword targets');
      }
      return response.json() as Promise<WordBankResponse[]>;
    },
    enabled: !!userId,
    refetchOnWindowFocus: false, // Prevent words from changing mid-game
    refetchOnMount: false,
    staleTime: Infinity,
  });
}
