// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export const getUserByIdKeys = {
  all: ['getUserById'] as const,
};

export function useGetUserById(params?: any) {
  return useQuery({
    queryKey: getUserByIdKeys.all,
    queryFn: () => api.get<any>('/users/' + params?.id),
  });
}
