// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface DailyProgressType {
  id: string;
  userId: string;
  date: string;
  targetQuestions: number;
  answeredQuestions: number;
  correctQuestions: number;
  wrongQuestions: number;
}

export interface DailyProgressFilterInput {
  id?: string;
  userId?: string;
  date?: string;
  startDate?: string;
  endDate?: string;
  targetQuestions?: number;
  answeredQuestions?: number;
  correctQuestions?: number;
  wrongQuestions?: number;
}

const QUERY = gql`
  query listDailyProgresses($filter: DailyProgressFilterInput) {
    listDailyProgresses(filter: $filter) {
      id
      userId
      date
      targetQuestions
      answeredQuestions
      correctQuestions
      wrongQuestions
    }
  }
`;

export const listDailyProgressesKeys = {
  all: ['listDailyProgresses'] as const,
  filtered: (filter: DailyProgressFilterInput) => ['listDailyProgresses', filter] as const,
};

export function useListDailyProgresses(filter?: DailyProgressFilterInput) {
  return useQuery({
    queryKey: filter ? listDailyProgressesKeys.filtered(filter) : listDailyProgressesKeys.all,
    queryFn: () => request<{ listDailyProgresses: DailyProgressType[] }>(GRAPHQL_ENDPOINT, QUERY, filter ? { filter } : {}).then(data => data.listDailyProgresses),
  });
}
