// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface ResponseType {
  [key: string]: unknown;
}

const QUERY = gql`
  query listQuizQuestions($filter: String) {
    listQuizQuestions(filter: $filter) {
      id
    }
  }
`;

export const listQuizQuestionsKeys = {
  all: ['listQuizQuestions'] as const,
  filtered: (filter: any) => ['listQuizQuestions', filter] as const,
};

export function useListQuizQuestions(filter?: any) {
  return useQuery({
    queryKey: filter ? listQuizQuestionsKeys.filtered(filter) : listQuizQuestionsKeys.all,
    queryFn: () => request<{ listQuizQuestions: ResponseType[] }>(GRAPHQL_ENDPOINT, QUERY, filter ? { filter } : {}).then(data => data.listQuizQuestions),
  });
}
