// AUTO-GENERATED by Frontend Engineer workflow
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export function useSubmitAnswer() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (payload: any) => api.post<void>('/submitAnswer', payload),
    onSuccess: () => {
      queryClient.invalidateQueries();
    },
  });
}
