// AUTO-GENERATED by Frontend Engineer workflow
import { useQuery } from '@tanstack/react-query';

export interface WordBankResponse {
  id: string;
  word: string;
  partOfSpeech?: string;
  translation?: string;
  targetLevel: string;
}

export const wordleTargetKeys = {
  all: ['wordleTarget'] as const,
  byUser: (userId: string) => ['wordleTarget', userId] as const,
};

export function useGetWordleTarget(userId?: string) {
  return useQuery({
    queryKey: userId ? wordleTargetKeys.byUser(userId) : wordleTargetKeys.all,
    queryFn: async () => {
      if (!userId) throw new Error('User ID is required');
      const response = await fetch(`/api/v1/users/${userId}:wordleTarget`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (!response.ok) {
        throw new Error('Failed to fetch wordle target');
      }
      return response.json() as Promise<WordBankResponse>;
    },
    enabled: !!userId,
    refetchOnWindowFocus: false, // Prevent word from changing mid-game
    refetchOnMount: false,
    staleTime: Infinity,
  });
}
