// AUTO-GENERATED by Frontend Engineer workflow
import React from 'react';
import { Renderer } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/error-review-board.render-schema.json';

export default function ErrorReviewBoardPage() {
  return <Renderer spec={spec} registry={componentRegistry} />;
}
