// AUTO-GENERATED by Frontend Engineer workflow
import React, { useEffect } from 'react';
import { Renderer, useStateStore, useStateValue } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/learning-dashboard.render-schema.json';
import { useListDailyProgresses } from '@/hooks/use-list-daily-progresses';

export default function LearningDashboardPage() {
  const store = useStateStore();
  const userId = store.get('/data/user/id') as string;
  const today = new Date().toISOString().split('T')[0];

  // Subscribe to dailyTargetQuestions so the effect re-runs when user data arrives
  const dailyTargetQuestions = useStateValue('/data/user/dailyTargetQuestions') as number | undefined;

  const { data: progresses } = useListDailyProgresses(userId ? { userId, date: today } : undefined);

  useEffect(() => {
    const current = store.get('/data/todayProgress') as any;
    const userDailyTarget = dailyTargetQuestions ?? 10;

    if (progresses && progresses.length > 0) {
      const p = progresses[0];
      if (current?.id !== p.id || current?.answeredQuestions !== p.answeredQuestions) {
        store.set('/data/todayProgress', p);
      }
    } else if (dailyTargetQuestions !== undefined) {
      // Prevent infinite loop: only update if the values are actually different
      const newAnswered = current?.answeredQuestions ?? 0;
      if (current?.answeredQuestions !== newAnswered || current?.targetQuestions !== userDailyTarget) {
        store.set('/data/todayProgress', { answeredQuestions: newAnswered, targetQuestions: userDailyTarget });
      }
    }
  }, [progresses, store, dailyTargetQuestions]);

  return <Renderer spec={spec} registry={componentRegistry} />;
}
