// AUTO-GENERATED by Frontend Engineer workflow
import React, { useEffect } from 'react';
import { Renderer, useStateStore } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/learning-dashboard.render-schema.json';
import { useListDailyProgresses } from '@/hooks/use-list-daily-progresses';

export default function LearningDashboardPage() {
  const store = useStateStore();
  const userId = store.get('/data/user/id') as string;
  const today = new Date().toISOString().split('T')[0];

  const { data: progresses } = useListDailyProgresses(userId ? { userId, date: today } : undefined);

  useEffect(() => {
    const current = store.get('/data/todayProgress') as any;
    const userDailyTarget = (store.get('/data/user') as any)?.dailyTargetQuestions ?? 10;

    if (progresses && progresses.length > 0) {
      const p = progresses[0];
      if (current?.id !== p.id || current?.answeredQuestions !== p.answeredQuestions) {
        store.set('/data/todayProgress', p);
      }
    } else {
      if (current?.answeredQuestions !== 0) {
        store.set('/data/todayProgress', { answeredQuestions: 0, targetQuestions: userDailyTarget });
      }
    }
  }, [progresses, store]);

  return <Renderer spec={spec} registry={componentRegistry} />;
}
