// AUTO-GENERATED by Frontend Engineer workflow
import React from 'react';
import { Renderer } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/memory-game.render-schema.json';

export default function MemoryGamePage() {
  return <Renderer spec={spec} registry={componentRegistry} />;
}
