// AUTO-GENERATED by Frontend Engineer workflow
import React, { useCallback, useEffect, useMemo, useRef } from 'react';
import { Renderer, useStateStore } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/quiz-board.render-schema.json';
import { useGetNextQuestion } from '@/hooks/use-get-next-question';

export default function QuizBoardPage() {
  const store = useStateStore();
  const userId = store.get('/data/user/id') as string;

  const { data: question, isLoading, refetch } = useGetNextQuestion(
    userId ? { userId } : undefined
  );

  // Shuffle the 4 answer options on each new question
  const shuffledOptions = useMemo(() => {
    if (!question) return [];
    const opts = [
      question.correctAnswer,
      question.distractor1,
      question.distractor2,
      question.distractor3,
    ].filter(Boolean);
    // Fisher-Yates shuffle
    for (let i = opts.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [opts[i], opts[j]] = [opts[j], opts[i]];
    }
    return opts;
  }, [question?.id]);

  useEffect(() => {
    if (question) {
      store.set('/data/activeQuestion', question);
      store.set('/data/activeQuestionId', question.id);
      store.set('/data/shuffledOptions', shuffledOptions);
      // Clear previous answer state
      store.set('/data/lastAnswerResult', null);
      store.set('/modals/explanation-modal', false);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [question?.id]);

  // Expose refetch so BehaviorProvider can call it after answer submission
  const loadNext = useCallback(() => { refetch(); }, [refetch]);
  const loadNextRef = useRef(loadNext);
  loadNextRef.current = loadNext;
  useEffect(() => {
    store.set('/actions/loadNextQuestion', () => loadNextRef.current());
  // Run only once on mount
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!userId) {
    return (
      <div className="flex h-full items-center justify-center text-muted-foreground">
        Loading...
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!question) {
    return (
      <div className="flex h-full items-center justify-center flex-col gap-4">
        <p className="text-xl text-muted-foreground">🎉 沒有題目了，今天已完成所有學習！</p>
      </div>
    );
  }

  return <Renderer spec={spec} registry={componentRegistry} />;
}
